# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calculator.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='calculator.proto',
  package='br.ufc.quixada.services',
  syntax='proto3',
  serialized_pb=_b('\n\x10\x63\x61lculator.proto\x12\x17\x62r.ufc.quixada.services\"\x94\x01\n\x07Request\x12\n\n\x02id\x18\x01 \x01(\x05\x12\n\n\x02n1\x18\x02 \x01(\x01\x12\n\n\x02n2\x18\x03 \x01(\x01\x12\x35\n\x02op\x18\x04 \x01(\x0e\x32).br.ufc.quixada.services.Request.Operacao\".\n\x08Operacao\x12\x07\n\x03SOM\x10\x00\x12\x07\n\x03SUB\x10\x01\x12\x07\n\x03MUL\x10\x02\x12\x07\n\x03\x44IV\x10\x03\" \n\x05Reply\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0b\n\x03res\x18\x02 \x01(\x01\x42&\n\x17\x62r.ufc.quixada.servicesB\x0b\x43\x61lculadorab\x06proto3')
)



_REQUEST_OPERACAO = _descriptor.EnumDescriptor(
  name='Operacao',
  full_name='br.ufc.quixada.services.Request.Operacao',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SOM', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SUB', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MUL', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DIV', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=148,
  serialized_end=194,
)
_sym_db.RegisterEnumDescriptor(_REQUEST_OPERACAO)


_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='br.ufc.quixada.services.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='br.ufc.quixada.services.Request.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='n1', full_name='br.ufc.quixada.services.Request.n1', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='n2', full_name='br.ufc.quixada.services.Request.n2', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='op', full_name='br.ufc.quixada.services.Request.op', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _REQUEST_OPERACAO,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=194,
)


_REPLY = _descriptor.Descriptor(
  name='Reply',
  full_name='br.ufc.quixada.services.Reply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='br.ufc.quixada.services.Reply.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='res', full_name='br.ufc.quixada.services.Reply.res', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=196,
  serialized_end=228,
)

_REQUEST.fields_by_name['op'].enum_type = _REQUEST_OPERACAO
_REQUEST_OPERACAO.containing_type = _REQUEST
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Reply'] = _REPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST,
  __module__ = 'calculator_pb2'
  # @@protoc_insertion_point(class_scope:br.ufc.quixada.services.Request)
  ))
_sym_db.RegisterMessage(Request)

Reply = _reflection.GeneratedProtocolMessageType('Reply', (_message.Message,), dict(
  DESCRIPTOR = _REPLY,
  __module__ = 'calculator_pb2'
  # @@protoc_insertion_point(class_scope:br.ufc.quixada.services.Reply)
  ))
_sym_db.RegisterMessage(Reply)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\027br.ufc.quixada.servicesB\013Calculadora'))
# @@protoc_insertion_point(module_scope)
